services:
  - type: web
    name: rockroot-tools-app
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/app/dev.sqlite
